# fly.toml app configuration file generated for get-bookd-server on 2023-06-13T03:00:33-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "get-bookd-server"
primary_region = "ewr"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[statics]]
  guest_path = "/data/mediafiles"
  url_prefix = "/data/media/"

[[mounts]]
  source = "data"
  destination = "/data/mediafiles/images"